apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    name: pod-2
spec:
  containers:
  - name: pod-2
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
