apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: pod-1
  ports:
  - port: 80 # Precisa fazer o port-forward com o kind / kubectl port-forward service/svc-pod-1 3001:80
    #targetPort: 80
    nodePort: 30000