apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
  - name: portal-noticia-container
    image: aluracursos/portal-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: portal-noticias-loadbalancer
spec:
  type: NodePort
  selector:
    app: portal-noticias
  ports:
  - port: 80
    nodePort: 30000