apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:
  containers:
  - name: sistema-noticias
    image: aluracursos/sistema-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: sistema-configmap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sistema-configmap
data:
  HOST_DB: svc-db-noticias:3306
  USER_DB: root
  PASS_DB: q1w2e3r4
  DATABASE_DB: empresa

---

apiVersion: v1
kind: Service
metadata:
  name: sistema-loadbalancer
spec:
  type: NodePort
  selector:
    app: sistema-noticias
  ports:
  - port: 80
    nodePort: 30001

---

apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
  - name: db-noticias
    image: mysql:8
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
    envFrom:
      - configMapRef:
          name: db-configmap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  MYSQL_ROOT_PASSWORD: q1w2e3r4
  MYSQL_DATABASE: empresa
  MYSQL_PASSWORD: q1w2e3r4

---

apiVersion: v1
kind: Service
metadata:
  name: svc-db-noticias
spec:
  type: ClusterIP
  selector:
    app: db-noticias
  ports:
  - port: 3306

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-noticias-configmap
data:
  IP_SISTEMA: http://localhost:3001

---

apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
  - name: portal-noticia-container
    image: aluracursos/portal-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: portal-noticias-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: portal-noticias-loadbalancer
spec:
  type: NodePort
  selector:
    app: portal-noticias
  ports:
  - port: 80
    nodePort: 30000